import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What AI models does WriteBot support?",
    answer: "WriteBot supports a wide range of industry-leading AI models, including ChatGPT-3.5, ChatGPT-4, GPT-4o, DALL-E 2 & 3, Stable Diffusion, Whisper for speech-to-text, and ElevenLabs for text-to-speech. We are constantly updating our platform with the latest and greatest models.",
  },
  {
    question: "Can I use my own OpenAI API key?",
    answer: "Yes, our platform supports the use of multiple OpenAI API keys, giving you the flexibility to manage your usage and costs directly.",
  },
  {
    question: "Is the content generated by WriteBot original?",
    answer: "We have an integrated AI Plagiarism Checker and AI Content Detector to help you verify the originality of your content. While AI-generated content is typically unique, we always recommend running it through these checks to ensure authenticity.",
  },
  {
    question: "What languages are supported?",
    answer: "WriteBot supports virtually unlimited languages. You can generate content for a global audience by simply selecting your desired language within the platform.",
  },
  {
    question: "What are the technical requirements?",
    answer: "WriteBot is a web-based SaaS platform, so all you need is a modern web browser. For self-hosted solutions, it requires PHP 8.1 (Apache recommended) and is built on the robust Laravel Framework.",
  },
  {
    question: "What payment gateways are accepted?",
    answer: "We accept a variety of payment gateways for your convenience, including PayPal, Stripe, PayTM, Razorpay, IyZico, Paystack, Flutterwave, and many more.",
  },
];

export function Faq() {
  return (
    <section className="py-20 sm:py-32">
      <div className="container mx-auto px-4 max-w-3xl">
        <div className="text-center">
          <h2 className="text-3xl font-extrabold tracking-tight sm:text-4xl font-headline">
            Frequently Asked Questions
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Have questions? We've got answers. If you can't find what you're looking for, feel free to contact our support team.
          </p>
        </div>
        <Accordion type="single" collapsible className="mt-12 w-full">
          {faqs.map((faq, index) => (
            <AccordionItem value={`item-${index}`} key={index}>
              <AccordionTrigger className="text-left">{faq.question}</AccordionTrigger>
              <AccordionContent className="text-base text-muted-foreground">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
